/**
 * RASQ Exercise Library v1 — code-first catalog (no database).
 * Stable exerciseId slugs map to future DB rows and CV measurement targets.
 */

export type BodyRegion = "knee" | "lumbar" | "shoulder";

export type ExerciseLibraryEntryV1 = {
  exerciseId: string;
  nameEn: string;
  nameAr: string;
  bodyRegion: BodyRegion;
  conditionCategory: string[];
  targetImpairment: string;
  functionalGoal: string;
  difficultyLevel: 1 | 2 | 3;
  defaultSets: number;
  defaultReps?: number | string;
  defaultDurationSec?: number;
  defaultRestSec: number;
  equipment: string[];
  precautions: string;
  contraindications?: string;
  whyThisMatters: string;
  patientInstructions: string;
  biomechanicalRationale: string;
  progressionCriteria: string;
  regressionCriteria: string;
  futureCvMeasurementTarget?: string;
  libraryVersion: "v1";
};

export const EXERCISE_LIBRARY_V1: ExerciseLibraryEntryV1[] = [
  // ── Knee (7) ──────────────────────────────────────────────────────────────
  {
    exerciseId: "quad-set",
    nameEn: "Quad Set / Activation",
    nameAr: "تفعيل عضلة الفخذ الأمامية",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee OA", "post-op knee"],
    targetImpairment: "Quadriceps activation deficit",
    functionalGoal: "Restore voluntary quad control before loaded movement",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Stop if sharp knee pain increases. Keep breathing steady.",
    whyThisMatters: "Waking up the front thigh muscle helps support the knee during daily activities.",
    patientInstructions:
      "Lie or sit with your leg straight. Tighten the muscle on the front of your thigh and press the back of your knee gently toward the surface. Hold 5 seconds, then relax. Repeat with controlled effort.",
    biomechanicalRationale:
      "Restores voluntary quadriceps activation and joint compression without high shear load.",
    progressionCriteria: "Ready for clinician progression review when hold is strong and pain-free for 10 reps.",
    regressionCriteria: "Reduce hold time or perform seated if pain or swelling increases.",
    futureCvMeasurementTarget: "knee extension activation",
    libraryVersion: "v1",
  },
  {
    exerciseId: "heel-slide",
    nameEn: "Heel Slide",
    nameAr: "انزلاق الكعب",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee stiffness", "post-op knee"],
    targetImpairment: "Limited knee flexion ROM",
    functionalGoal: "Improve knee bending for sitting and stairs",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultReps: 15,
    defaultRestSec: 45,
    equipment: ["Non-slip surface"],
    precautions: "Move within a comfortable range. Do not force into pain.",
    whyThisMatters: "Gentle bending helps you sit, walk, and climb stairs more comfortably.",
    patientInstructions:
      "Lie on your back with legs extended. Slowly slide your heel toward your buttock, bending the knee. Hold briefly at end range, then slide back. Keep movements smooth.",
    biomechanicalRationale: "Low-load flexion mobilization with minimal weight-bearing stress.",
    progressionCriteria: "Ready for clinician progression review when flexion improves with stable pain response.",
    regressionCriteria: "Reduce range or reps if flexion causes sharp pain.",
    futureCvMeasurementTarget: "knee flexion ROM",
    libraryVersion: "v1",
  },
  {
    exerciseId: "sit-to-stand",
    nameEn: "Sit-to-Stand",
    nameAr: "الجلوس والوقوف",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee OA", "general knee rehab"],
    targetImpairment: "Sit-to-stand weakness",
    functionalGoal: "Stand from a chair safely and independently",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSec: 60,
    equipment: ["Sturdy chair"],
    precautions: "Use chair arms only for balance, not to pull up. Stop if knee gives way.",
    whyThisMatters: "Standing from a chair is essential for daily independence and builds leg strength.",
    patientInstructions:
      "Sit at the edge of a sturdy chair, feet shoulder-width apart. Lean forward slightly, push through your heels, and stand up fully. Lower back to sitting with control.",
    biomechanicalRationale: "Functional closed-chain movement integrating quad, glute, and trunk control.",
    progressionCriteria: "Ready for clinician progression review when form stays controlled for full set.",
    regressionCriteria: "Use higher seat or reduce reps if pain or instability increases.",
    futureCvMeasurementTarget: "sit-to-stand symmetry",
    libraryVersion: "v1",
  },
  {
    exerciseId: "mini-squat",
    nameEn: "Mini Squat (0–45°)",
    nameAr: "قرفصاء صغيرة",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee OA", "patellofemoral"],
    targetImpairment: "Knee control in partial flexion",
    functionalGoal: "Build controlled knee bending during functional tasks",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSec: 60,
    equipment: [],
    precautions: "Keep knees aligned over toes. Stop if sharp or increasing pain.",
    whyThisMatters: "Controlled squatting prepares your knee for stairs, lifting, and daily movement.",
    patientInstructions:
      "Stand with feet shoulder-width apart. Slowly bend knees to about 45°, keeping chest tall and weight through heels. Hold 2 seconds, return to standing.",
    biomechanicalRationale: "Partial squat loads patellofemoral and tibiofemoral joints within controlled range.",
    progressionCriteria: "Ready for clinician progression review when depth and alignment remain consistent.",
    regressionCriteria: "Reduce depth or use chair support if valgus or pain increases.",
    futureCvMeasurementTarget: "knee flexion angle, valgus control",
    libraryVersion: "v1",
  },
  {
    exerciseId: "heel-raise",
    nameEn: "Heel Raises",
    nameAr: "رفع الكعب",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "calf weakness", "balance"],
    targetImpairment: "Calf endurance deficit",
    functionalGoal: "Improve push-off for walking and stairs",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 20,
    defaultRestSec: 45,
    equipment: ["Chair for balance"],
    precautions: "Hold support if balance is uncertain. Lower slowly.",
    whyThisMatters: "Strong calves help you walk, climb stairs, and balance on your toes.",
    patientInstructions:
      "Stand behind a chair for support. Rise onto the balls of both feet, hold 2 seconds, lower with control. Keep weight even through both feet.",
    biomechanicalRationale: "Ankle plantarflexor strengthening supports gait propulsion and knee stability.",
    progressionCriteria: "Ready for clinician progression review when full set completed without fatigue-related form loss.",
    regressionCriteria: "Reduce reps or use bilateral support only.",
    futureCvMeasurementTarget: "calf raise height symmetry",
    libraryVersion: "v1",
  },
  {
    exerciseId: "single-leg-stance",
    nameEn: "Single Leg Stance",
    nameAr: "الوقوف على رجل واحدة",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "balance", "ankle-knee stability"],
    targetImpairment: "Single-leg balance deficit",
    functionalGoal: "Improve stability during single-leg weight bearing",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultDurationSec: 30,
    defaultRestSec: 45,
    equipment: ["Wall or chair nearby"],
    precautions: "Stand near support. Stop if dizziness or sharp pain occurs.",
    whyThisMatters: "Balance on one leg is needed for walking, turning, and safe movement.",
    patientInstructions:
      "Stand on one leg with a slight knee bend. Hold your balance for the prescribed time. Use wall or chair lightly if needed. Minimise hip drop on the lifted side.",
    biomechanicalRationale: "Challenges hip-knee-ankle neuromuscular control in functional single-limb stance.",
    progressionCriteria: "Ready for clinician progression review when hold time meets target with level pelvis.",
    regressionCriteria: "Reduce hold time or keep fingertip support.",
    futureCvMeasurementTarget: "balance, hip drop",
    libraryVersion: "v1",
  },
  {
    exerciseId: "step-up",
    nameEn: "Low Step-Up",
    nameAr: "صعود على درجة منخفضة",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "functional strength"],
    targetImpairment: "Step-up strength and control",
    functionalGoal: "Climb stairs and steps with confidence",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 60,
    equipment: ["Step 15–20 cm"],
    precautions: "Use a stable step. Drive through the heel. Step down with control.",
    whyThisMatters: "Step-ups build the strength you need for stairs and curbs in daily life.",
    patientInstructions:
      "Face a low step. Step up with your leading leg, drive through the heel to straighten the knee. Step down slowly. Keep trunk upright.",
    biomechanicalRationale: "Unilateral closed-chain loading mimics stair ascent with modifiable step height.",
    progressionCriteria: "Ready for clinician progression review when step height and reps tolerated with good alignment.",
    regressionCriteria: "Lower step height or reduce reps if knee pain increases.",
    futureCvMeasurementTarget: "step height, knee valgus",
    libraryVersion: "v1",
  },

  // ── Lumbar (7) ────────────────────────────────────────────────────────────
  {
    exerciseId: "diaphragmatic-breathing",
    nameEn: "Diaphragmatic Breathing",
    nameAr: "التنفس الحجابي",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "core activation", "stress-related tension"],
    targetImpairment: "Poor breathing pattern / trunk bracing",
    functionalGoal: "Calm system and support gentle core activation",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultDurationSec: 300,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Breathe comfortably. Do not force breath holds.",
    whyThisMatters: "Relaxed breathing can reduce muscle tension and help you move more comfortably.",
    patientInstructions:
      "Lie on your back with knees bent. Place one hand on your chest and one on your belly. Breathe in slowly through your nose so your belly rises. Exhale gently through your mouth.",
    biomechanicalRationale: "Diaphragmatic breathing supports parasympathetic tone and baseline core coordination.",
    progressionCriteria: "Ready for clinician progression review when pattern is consistent without breath holding.",
    regressionCriteria: "Shorten duration or perform seated if lying is uncomfortable.",
    libraryVersion: "v1",
  },
  {
    exerciseId: "pelvic-tilt",
    nameEn: "Pelvic Tilt",
    nameAr: "ميل الحوض",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "lumbar stiffness"],
    targetImpairment: "Limited lumbar-pelvic control",
    functionalGoal: "Improve awareness of neutral spine position",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultReps: 15,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Move gently. Stay within a pain-free range.",
    whyThisMatters: "Learning to move your pelvis gently helps reduce stiffness and supports safer bending.",
    patientInstructions:
      "Lie on your back, knees bent. Flatten your lower back toward the floor by gently tilting your pelvis. Hold 3 seconds, then release. Move slowly.",
    biomechanicalRationale: "Low-load lumbopelvic mobilization for motor control of lumbar flexion-extension.",
    progressionCriteria: "Ready for clinician progression review when movement is smooth and symptom-stable.",
    regressionCriteria: "Reduce range if extension or flexion provokes symptoms.",
    futureCvMeasurementTarget: "lumbar flexion control",
    libraryVersion: "v1",
  },
  {
    exerciseId: "cat-cow",
    nameEn: "Cat-Cow",
    nameAr: "قطّة-بقرة",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "thoracic-lumbar mobility"],
    targetImpairment: "Spinal stiffness",
    functionalGoal: "Improve gentle spinal movement",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSec: 30,
    equipment: ["Mat"],
    precautions: "Avoid end-range pinching. Move with breath.",
    whyThisMatters: "Gentle arching and rounding keeps your spine moving comfortably through the day.",
    patientInstructions:
      "On hands and knees, arch your back up like a cat, then slowly drop your belly and lift your chest. Move between positions with your breath.",
    biomechanicalRationale: "Alternating flexion-extension mobilization through low shear positions.",
    progressionCriteria: "Ready for clinician progression review when full range is comfortable.",
    regressionCriteria: "Reduce range if wrist or knee loading is problematic — modify position.",
    futureCvMeasurementTarget: "spinal segment motion",
    libraryVersion: "v1",
  },
  {
    exerciseId: "glute-bridge",
    nameEn: "Glute Bridge",
    nameAr: "جسر الأرداف",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "hip weakness"],
    targetImpairment: "Hip extension weakness",
    functionalGoal: "Strengthen glutes to support the lower back",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSec: 45,
    equipment: ["Mat"],
    precautions: "Do not over-arch the lower back at the top. Squeeze glutes, not low back.",
    whyThisMatters: "Strong glutes help support your lower back when you stand, walk, and lift.",
    patientInstructions:
      "Lie on your back, knees bent, feet flat. Lift your hips until shoulders, hips, and knees align. Squeeze your glutes at the top. Lower slowly.",
    biomechanicalRationale: "Hip extension strengthening with reduced lumbar compression vs loaded squatting.",
    progressionCriteria: "Ready for clinician progression review when bridges are stable without cramping.",
    regressionCriteria: "Reduce height or perform partial range if hamstring cramp occurs.",
    futureCvMeasurementTarget: "hip extension, lumbar neutral",
    libraryVersion: "v1",
  },
  {
    exerciseId: "bird-dog",
    nameEn: "Bird-Dog",
    nameAr: "طائر-كلب",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "core stability"],
    targetImpairment: "Trunk stability deficit",
    functionalGoal: "Build core and hip control during arm/leg movement",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Mat"],
    precautions: "Keep trunk steady — avoid rocking. Stop if back pain increases.",
    whyThisMatters: "This exercise trains your core to stay stable while your arms and legs move.",
    patientInstructions:
      "On hands and knees, extend opposite arm and leg while keeping your trunk level. Hold 3 seconds, return, switch sides. Move slowly.",
    biomechanicalRationale: "Anti-rotation and anti-extension challenge for deep stabilizers.",
    progressionCriteria: "Ready for clinician progression review when trunk stays level for full set.",
    regressionCriteria: "Lift arm or leg only (not both) if form breaks down.",
    futureCvMeasurementTarget: "trunk stability",
    libraryVersion: "v1",
  },
  {
    exerciseId: "hip-hinge",
    nameEn: "Hip Hinge (education)",
    nameAr: "ميل الورك",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "movement retraining"],
    targetImpairment: "Poor hip vs lumbar dissociation",
    functionalGoal: "Learn safe bending pattern using hips",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Wall or dowel optional"],
    precautions: "Keep spine neutral. Hinge at hips, not low back.",
    whyThisMatters: "Bending from your hips protects your lower back during daily tasks.",
    patientInstructions:
      "Stand with feet hip-width apart. Push hips back while keeping a slight knee bend and neutral spine, as if closing a door with your hips. Return to standing.",
    biomechanicalRationale: "Motor retraining for hip-dominant flexion reducing lumbar flexion moment.",
    progressionCriteria: "Ready for clinician progression review when pattern is consistent without lumbar rounding.",
    regressionCriteria: "Reduce range or use wall feedback if lumbar flexion occurs.",
    futureCvMeasurementTarget: "hip vs lumbar flexion",
    libraryVersion: "v1",
  },
  {
    exerciseId: "walking-tolerance",
    nameEn: "Walking Tolerance",
    nameAr: "تحمل المشي",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "deconditioning"],
    targetImpairment: "Reduced walking endurance",
    functionalGoal: "Build safe walking duration for daily activities",
    difficultyLevel: 1,
    defaultSets: 1,
    defaultDurationSec: 600,
    defaultRestSec: 0,
    equipment: [],
    precautions: "Walk at a comfortable pace. Stop and rest if symptoms flare beyond baseline.",
    whyThisMatters: "Gradual walking helps you return to daily activities and supports overall recovery.",
    patientInstructions:
      "Walk at a comfortable pace on flat ground for the prescribed time. Stand tall, let arms swing naturally. Rest as needed.",
    biomechanicalRationale: "Low-impact aerobic loading for tissue tolerance and confidence.",
    progressionCriteria: "Ready for clinician progression review when duration increases without symptom flare.",
    regressionCriteria: "Reduce time or break into shorter intervals.",
    futureCvMeasurementTarget: "gait speed, posture",
    libraryVersion: "v1",
  },

  // ── Shoulder (6) ─────────────────────────────────────────────────────────
  {
    exerciseId: "pendulum",
    nameEn: "Pendulum Exercise",
    nameAr: "تأرجح الذراع",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder pain", "post-op shoulder", "frozen shoulder"],
    targetImpairment: "Shoulder stiffness",
    functionalGoal: "Gentle passive shoulder mobility",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultDurationSec: 120,
    defaultRestSec: 30,
    equipment: ["Table or chair for support"],
    precautions: "Let arm hang relaxed. Do not force circular motion.",
    whyThisMatters: "Gentle swinging helps loosen a stiff shoulder without heavy muscle effort.",
    patientInstructions:
      "Lean forward, support yourself with the unaffected arm on a table. Let the affected arm hang and gently swing in small circles. Keep shoulder relaxed.",
    biomechanicalRationale: "Gravity-assisted passive mobility with minimal active contraction.",
    progressionCriteria: "Ready for clinician progression review when range improves comfortably.",
    regressionCriteria: "Smaller circles or shorter duration if pain increases.",
    libraryVersion: "v1",
  },
  {
    exerciseId: "scapular-setting",
    nameEn: "Scapular Setting",
    nameAr: "تثبيت الكتف",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder impingement", "posture", "rotator cuff"],
    targetImpairment: "Scapular dyskinesis",
    functionalGoal: "Improve shoulder blade control and posture",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Do not shrug toward ears. Gentle squeeze downward and back.",
    whyThisMatters: "Good shoulder blade position supports healthy shoulder movement and posture.",
    patientInstructions:
      "Sit or stand tall. Gently draw shoulder blades down and slightly together, as if putting them in back pockets. Hold 5 seconds, relax.",
    biomechanicalRationale: "Activates lower trapezius and serratus for scapular stability.",
    progressionCriteria: "Ready for clinician progression review when hold is consistent without upper trap dominance.",
    regressionCriteria: "Shorter holds if neck tension occurs.",
    futureCvMeasurementTarget: "scapular position",
    libraryVersion: "v1",
  },
  {
    exerciseId: "table-slide",
    nameEn: "Table Slides (Flexion)",
    nameAr: "انزلاق على الطاولة",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder stiffness", "post-op shoulder"],
    targetImpairment: "Limited shoulder flexion",
    functionalGoal: "Improve reaching overhead safely",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSec: 45,
    equipment: ["Table"],
    precautions: "Slide within comfort. Do not force overhead range.",
    whyThisMatters: "Table slides help you regain reaching movement with support and less pain.",
    patientInstructions:
      "Sit at a table, place hands on a towel. Slide hands forward along the table, allowing arms to rise. Go to comfortable height, then slide back.",
    biomechanicalRationale: "Assisted flexion reduces active torque while improving ROM.",
    progressionCriteria: "Ready for clinician progression review when flexion range improves steadily.",
    regressionCriteria: "Reduce slide distance if pinching occurs.",
    futureCvMeasurementTarget: "shoulder flexion ROM",
    libraryVersion: "v1",
  },
  {
    exerciseId: "external-rotation",
    nameEn: "External Rotation (Band)",
    nameAr: "دوران خارجي",
    bodyRegion: "shoulder",
    conditionCategory: ["rotator cuff", "shoulder stability"],
    targetImpairment: "Rotator cuff weakness",
    functionalGoal: "Strengthen outward rotation for shoulder stability",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSec: 45,
    equipment: ["Resistance band", "Towel roll under arm optional"],
    precautions: "Keep elbow at side. Slow controlled movement. Light resistance only.",
    whyThisMatters: "Strong rotator cuff muscles help keep the shoulder stable during daily tasks.",
    patientInstructions:
      "Elbow bent at 90°, tucked at your side. Rotate forearm outward against band resistance. Return slowly. Keep elbow fixed.",
    biomechanicalRationale: "Targets infraspinatus/teres minor for glenohumeral stability.",
    progressionCriteria: "Ready for clinician progression review when full set with good form.",
    regressionCriteria: "Lighter band or fewer reps if pain at end range.",
    futureCvMeasurementTarget: "external rotation ROM",
    libraryVersion: "v1",
  },
  {
    exerciseId: "wall-slide",
    nameEn: "Wall Slides",
    nameAr: "انزلاق على الحائط",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder impingement", "posture"],
    targetImpairment: "Overhead mobility with poor scapular control",
    functionalGoal: "Improve overhead reach with scapular upward rotation",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Wall"],
    precautions: "Keep contact with wall. Do not arch lower back excessively.",
    whyThisMatters: "Wall slides train safe overhead movement with good posture.",
    patientInstructions:
      "Stand with back against wall, arms in W shape. Slide arms up the wall toward a Y shape, then back down. Keep wrists and elbows near wall.",
    biomechanicalRationale: "Combines flexion with scapular upward rotation in closed-environment feedback.",
    progressionCriteria: "Ready for clinician progression review when overhead range improves without compensation.",
    regressionCriteria: "Partial range if lumbar extension or pain occurs.",
    futureCvMeasurementTarget: "scapular upward rotation",
    libraryVersion: "v1",
  },
  {
    exerciseId: "posture-reset",
    nameEn: "Posture Reset",
    nameAr: "إعادة ضبط الوضعية",
    bodyRegion: "shoulder",
    conditionCategory: ["posture", "neck-shoulder tension"],
    targetImpairment: "Forward head / rounded shoulder posture",
    functionalGoal: "Practice neutral alignment for daily activities",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultDurationSec: 30,
    defaultRestSec: 20,
    equipment: [],
    precautions: "Gentle chin tuck — do not force neck backward.",
    whyThisMatters: "Good posture reduces strain on your neck and shoulders during the day.",
    patientInstructions:
      "Sit or stand tall. Gently draw chin back, lengthen spine, relax shoulders down. Breathe steadily and hold comfortable alignment.",
    biomechanicalRationale: "Cervicothoracic alignment retraining for load distribution.",
    progressionCriteria: "Ready for clinician progression review when posture can be maintained during light activity.",
    regressionCriteria: "Shorter holds if neck tension occurs.",
    libraryVersion: "v1",
  },
];

const LIBRARY_BY_ID = new Map(EXERCISE_LIBRARY_V1.map((e) => [e.exerciseId, e]));

export function getLibraryExerciseById(exerciseId: string): ExerciseLibraryEntryV1 | null {
  return LIBRARY_BY_ID.get(exerciseId) ?? null;
}

export function getLibraryExercisesByRegion(region: BodyRegion | "all"): ExerciseLibraryEntryV1[] {
  if (region === "all") return EXERCISE_LIBRARY_V1;
  return EXERCISE_LIBRARY_V1.filter((e) => e.bodyRegion === region);
}
