/**
 * RASQ Exercise Library v1 — code-first catalog (no database).
 * Stable exerciseId slugs map to future DB rows and CV measurement targets.
 */

export type BodyRegion = "knee" | "lumbar" | "shoulder";

export type ExerciseLibraryEntryV1 = {
  exerciseId: string;
  nameEn: string;
  nameAr: string;
  bodyRegion: BodyRegion;
  conditionCategory: string[];
  targetImpairment: string;
  functionalGoal: string;
  difficultyLevel: 1 | 2 | 3;
  defaultSets: number;
  defaultReps?: number | string;
  defaultDurationSec?: number;
  defaultRestSec: number;
  equipment: string[];
  precautions: string;
  /** Patient-facing stop-if guidance (Arabic) */
  precautionsAr: string;
  contraindications?: string;
  whyThisMatters: string;
  whyThisMattersAr: string;
  patientInstructions: string;
  patientInstructionsAr: string;
  biomechanicalRationale: string;
  progressionCriteria: string;
  regressionCriteria: string;
  futureCvMeasurementTarget?: string;
  libraryVersion: "v1";
};

export const EXERCISE_LIBRARY_V1: ExerciseLibraryEntryV1[] = [
  // ── Knee (10) ─────────────────────────────────────────────────────────────
  {
    exerciseId: "quad-set",
    nameEn: "Quad Set / Activation",
    nameAr: "تفعيل عضلة الفخذ الأمامية",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee OA", "post-op knee"],
    targetImpairment: "Quadriceps activation deficit",
    functionalGoal: "Restore voluntary quad control before loaded movement",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Stop if sharp knee pain increases. Keep breathing steady.",
    precautionsAr: "توقّف إذا زاد الألم الحاد في الركبة. حافظ على تنفسك هادئاً ومنتظماً.",
    contraindications: "Acute knee effusion with inability to activate quad; severe post-operative restrictions unless cleared by surgeon.",
    whyThisMatters: "Waking up the front thigh muscle helps support the knee during daily activities.",
    whyThisMattersAr: "تفعيل عضلة الفخذ الأمامية يساعد على دعم الركبة في حركاتك اليومية.",
    patientInstructions:
      "Lie or sit with your leg straight. Tighten the muscle on the front of your thigh and press the back of your knee gently toward the surface. Hold 5 seconds, then relax. Repeat with controlled effort.",
    patientInstructionsAr: "استلقِ أو اجلس ومدّ ساقك. شدّ عضلة مقدمة الفخذ واضغط بظهر ركبتك بلطف نحو السطح. ثبّت 5 ثوانٍ ثم ارخِ. كرّر بحركة بطيئة وتحكم.",
    biomechanicalRationale:
      "Restores voluntary quadriceps activation and joint compression without high shear load.",
    progressionCriteria: "Ready for clinician progression review when hold is strong and pain-free for 10 reps.",
    regressionCriteria: "Reduce hold time or perform seated if pain or swelling increases.",
    futureCvMeasurementTarget: "knee extension activation",
    libraryVersion: "v1",
  },
  {
    exerciseId: "heel-slide",
    nameEn: "Heel Slide",
    nameAr: "انزلاق الكعب",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee stiffness", "post-op knee"],
    targetImpairment: "Limited knee flexion ROM",
    functionalGoal: "Improve knee bending for sitting and stairs",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultReps: 15,
    defaultRestSec: 45,
    equipment: ["Non-slip surface"],
    precautions: "Move within a comfortable range. Do not force into pain.",
    precautionsAr: "تحرّك ضمن مدى مريح. لا تُجبر الركبة على مدى يسبب ألماً.",
    contraindications: "Recent knee surgery before flexion clearance; suspected meniscal block with locking.",
    whyThisMatters: "Gentle bending helps you sit, walk, and climb stairs more comfortably.",
    whyThisMattersAr: "ثني الركبة بلطف يساعدك على الجلوس والمشي وصعود الدرج براحة أكبر.",
    patientInstructions:
      "Lie on your back with legs extended. Slowly slide your heel toward your buttock, bending the knee. Hold briefly at end range, then slide back. Keep movements smooth.",
    patientInstructionsAr: "استلقِ على ظهرك ومدّ ساقيك. انزلق كعبك ببطء نحو الأرداف لثني الركبة. ثبّت لحظة عند نهاية المدى ثم ارجع. حافظ على حركة ناعمة.",
    biomechanicalRationale: "Low-load flexion mobilization with minimal weight-bearing stress.",
    progressionCriteria: "Ready for clinician progression review when flexion improves with stable pain response.",
    regressionCriteria: "Reduce range or reps if flexion causes sharp pain.",
    futureCvMeasurementTarget: "knee flexion ROM",
    libraryVersion: "v1",
  },
  {
    exerciseId: "sit-to-stand",
    nameEn: "Sit-to-Stand",
    nameAr: "الجلوس والوقوف",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee OA", "general knee rehab"],
    targetImpairment: "Sit-to-stand weakness",
    functionalGoal: "Stand from a chair safely and independently",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSec: 60,
    equipment: ["Sturdy chair"],
    precautions: "Use chair arms only for balance, not to pull up. Stop if knee gives way.",
    precautionsAr: "استخدم ذراعي الكرسي للتوازن فقط، لا للسحب. توقّف إذا شعرت أن الركبة تخذل.",
    contraindications: "Non–weight-bearing status; severe balance impairment without supervision.",
    whyThisMatters: "Standing from a chair is essential for daily independence and builds leg strength.",
    whyThisMattersAr: "الوقوف من الكرسي ضروري للاستقلالية اليومية ويقوّي ساقيك.",
    patientInstructions:
      "Sit at the edge of a sturdy chair, feet shoulder-width apart. Lean forward slightly, push through your heels, and stand up fully. Lower back to sitting with control.",
    patientInstructionsAr: "اجلس على حافة كرسي ثابت، قدمان بعرض الكتفين. انحنِ قليلاً للأمام وادفع بكعبيك للوقوف كاملاً. انزل للجلوس بتحكم.",
    biomechanicalRationale: "Functional closed-chain movement integrating quad, glute, and trunk control.",
    progressionCriteria: "Ready for clinician progression review when form stays controlled for full set.",
    regressionCriteria: "Use higher seat or reduce reps if pain or instability increases.",
    futureCvMeasurementTarget: "sit-to-stand symmetry",
    libraryVersion: "v1",
  },
  {
    exerciseId: "mini-squat",
    nameEn: "Mini Squat (0–45°)",
    nameAr: "قرفصاء صغيرة",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee OA", "patellofemoral"],
    targetImpairment: "Knee control in partial flexion",
    functionalGoal: "Build controlled knee bending during functional tasks",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSec: 60,
    equipment: [],
    precautions: "Keep knees aligned over toes. Stop if sharp or increasing pain.",
    precautionsAr: "حافظ على محاذاة الركبتين مع أصابع القدم. توقّف عند ألم حاد أو متزايد.",
    contraindications: "Acute patellar instability; weight-bearing restrictions.",
    whyThisMatters: "Controlled squatting prepares your knee for stairs, lifting, and daily movement.",
    whyThisMattersAr: "القرفصاء المتحكّم يُعدّ ركبتك للدرج والرفع والحركة اليومية.",
    patientInstructions:
      "Stand with feet shoulder-width apart. Slowly bend knees to about 45°, keeping chest tall and weight through heels. Hold 2 seconds, return to standing.",
    patientInstructionsAr: "قف بقدمين بعرض الكتفين. اثنِ ركبتيك ببطء إلى نحو 45°، مع استقامة الصدر ووزن الجسم على الكعبين. ثبّت ثانيتين ثم قف.",
    biomechanicalRationale: "Partial squat loads patellofemoral and tibiofemoral joints within controlled range.",
    progressionCriteria: "Ready for clinician progression review when depth and alignment remain consistent.",
    regressionCriteria: "Reduce depth or use chair support if valgus or pain increases.",
    futureCvMeasurementTarget: "knee flexion angle, valgus control",
    libraryVersion: "v1",
  },
  {
    exerciseId: "heel-raise",
    nameEn: "Heel Raises",
    nameAr: "رفع الكعب",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "calf weakness", "balance"],
    targetImpairment: "Calf endurance deficit",
    functionalGoal: "Improve push-off for walking and stairs",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 20,
    defaultRestSec: 45,
    equipment: ["Chair for balance"],
    precautions: "Hold support if balance is uncertain. Lower slowly.",
    precautionsAr: "امسك بالدعم إذا كان توازنك غير ثابت. انزل ببطء.",
    contraindications: "Achilles tendon rupture repair early phase; acute calf tear.",
    whyThisMatters: "Strong calves help you walk, climb stairs, and balance on your toes.",
    whyThisMattersAr: "عضلات الساق القوية تساعدك على المشي وصعود الدرج والتوازن على أطراف القدم.",
    patientInstructions:
      "Stand behind a chair for support. Rise onto the balls of both feet, hold 2 seconds, lower with control. Keep weight even through both feet.",
    patientInstructionsAr: "قف خلف كرسي للدعم. ارتفع على مقدمة القدمين، ثبّت ثانيتين، ثم انزل بتحكم. وزّع الوزن بالتساوي على القدمين.",
    biomechanicalRationale: "Ankle plantarflexor strengthening supports gait propulsion and knee stability.",
    progressionCriteria: "Ready for clinician progression review when full set completed without fatigue-related form loss.",
    regressionCriteria: "Reduce reps or use bilateral support only.",
    futureCvMeasurementTarget: "calf raise height symmetry",
    libraryVersion: "v1",
  },
  {
    exerciseId: "single-leg-stance",
    nameEn: "Single Leg Stance",
    nameAr: "الوقوف على رجل واحدة",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "balance", "ankle-knee stability"],
    targetImpairment: "Single-leg balance deficit",
    functionalGoal: "Improve stability during single-leg weight bearing",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultDurationSec: 30,
    defaultRestSec: 45,
    equipment: ["Wall or chair nearby"],
    precautions: "Stand near support. Stop if dizziness or sharp pain occurs.",
    precautionsAr: "قف قريباً من دعم. توقّف عند دوخة أو ألم حاد.",
    contraindications: "Severe vestibular symptoms; non–weight-bearing limb status.",
    whyThisMatters: "Balance on one leg is needed for walking, turning, and safe movement.",
    whyThisMattersAr: "التوازن على رجل واحدة مطلوب للمشي والدوران والحركة الآمنة.",
    patientInstructions:
      "Stand on one leg with a slight knee bend. Hold your balance for the prescribed time. Use wall or chair lightly if needed. Minimise hip drop on the lifted side.",
    patientInstructionsAr: "قف على رجل واحدة مع ثني بسيط في الركبة. ثبّت توازنك للمدة المحددة. استخدم الحائط أو الكرسي بلطف عند الحاجة. قلّل هبوط الحوض.",
    biomechanicalRationale: "Challenges hip-knee-ankle neuromuscular control in functional single-limb stance.",
    progressionCriteria: "Ready for clinician progression review when hold time meets target with level pelvis.",
    regressionCriteria: "Reduce hold time or keep fingertip support.",
    futureCvMeasurementTarget: "balance, hip drop",
    libraryVersion: "v1",
  },
  {
    exerciseId: "step-up",
    nameEn: "Low Step-Up",
    nameAr: "صعود على درجة منخفضة",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "functional strength"],
    targetImpairment: "Step-up strength and control",
    functionalGoal: "Climb stairs and steps with confidence",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 60,
    equipment: ["Step 15–20 cm"],
    precautions: "Use a stable step. Drive through the heel. Step down with control.",
    precautionsAr: "استخدم درجة ثابتة. ادفع بكعبك. انزل بتحكم.",
    contraindications: "Lower-extremity non–weight-bearing orders; unsteady gait without assistive device clearance.",
    whyThisMatters: "Step-ups build the strength you need for stairs and curbs in daily life.",
    whyThisMattersAr: "صعود الدرج يبني القوة التي تحتاجها للسلالم والارتفاعات في حياتك اليومية.",
    patientInstructions:
      "Face a low step. Step up with your leading leg, drive through the heel to straighten the knee. Step down slowly. Keep trunk upright.",
    patientInstructionsAr: "واجه درجة منخفضة. اصعد بالرجل الأمامية وادفع بكعبك لمدّ الركبة. انزل ببطء. حافظ على استقامة الجذع.",
    biomechanicalRationale: "Unilateral closed-chain loading mimics stair ascent with modifiable step height.",
    progressionCriteria: "Ready for clinician progression review when step height and reps tolerated with good alignment.",
    regressionCriteria: "Lower step height or reduce reps if knee pain increases.",
    futureCvMeasurementTarget: "step height, knee valgus",
    libraryVersion: "v1",
  },
  {
    exerciseId: "terminal-knee-extension",
    nameEn: "Terminal Knee Extension",
    nameAr: "تمديد الركبة النهائي",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "post-op knee", "knee extension lag"],
    targetImpairment: "Terminal extension deficit / extension lag",
    functionalGoal: "Restore full knee straightening for stable walking",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSec: 45,
    equipment: ["Resistance band", "Towel roll optional"],
    precautions: "Keep thigh still. Extend only at the knee. Stop if sharp anterior knee pain.",
    precautionsAr: "ثبّت الفخذ. مدّ الركبة فقط. توقّف عند ألم حاد أمام الركبة.",
    contraindications: "Post-operative range restrictions limiting extension; acute patellar tendinopathy flare.",
    whyThisMatters: "Full knee straightening helps you walk evenly and feel stable when standing.",
    whyThisMattersAr: "مدّ الركبة بالكامل يساعدك على المشي بتوازن والشعور بالثبات عند الوقوف.",
    patientInstructions:
      "Loop a band behind the knee or use a fixed point. Sit or stand with thigh supported. Straighten the knee fully, squeeze the front thigh for 3 seconds, then return slowly. Keep hip still.",
    patientInstructionsAr: "ضع شريطاً خلف الركبة أو نقطة ثابتة. اجلس أو قف مع دعم الفخذ. مدّ الركبة كاملة، شدّ مقدمة الفخذ 3 ثوانٍ، ثم ارجع ببطء. ثبّت الورك.",
    biomechanicalRationale:
      "Isolated terminal extension training reduces extension lag with low compressive load.",
    progressionCriteria: "Ready for clinician progression review when full extension is held without pain for full set.",
    regressionCriteria: "Reduce band tension or perform without band if irritation increases.",
    futureCvMeasurementTarget: "knee extension angle, extension lag",
    libraryVersion: "v1",
  },
  {
    exerciseId: "short-arc-quad",
    nameEn: "Short Arc Quad",
    nameAr: "تقوية الفخذ الأمامية بمدى قصير",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "post-op knee", "patellofemoral"],
    targetImpairment: "Quadriceps weakness in mid-range extension",
    functionalGoal: "Build quad strength before full-range loading",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSec: 45,
    equipment: ["Bolster or rolled towel"],
    precautions: "Do not lift the thigh off the roll. Lower with control.",
    precautionsAr: "لا ترفع الفخذ عن اللفافة. انزل بتحكم.",
    contraindications: "Acute patellar pain with loaded extension; surgeon restrictions on active extension.",
    whyThisMatters: "Strengthening in a safe range protects the kneecap while rebuilding thigh strength.",
    whyThisMattersAr: "التقوية في مدى آمن تحمي الرضفة وتعيد بناء قوة الفخذ.",
    patientInstructions:
      "Lie on your back with a rolled towel under the knee. Straighten the knee to lift the foot, hold 3 seconds at the top, then lower slowly. Keep the back of the knee on the roll.",
    patientInstructionsAr: "استلقِ على ظهرك مع لفافة تحت الركبة. مدّ الركبة لرفع القدم، ثبّت 3 ثوانٍ في الأعلى، ثم انزل ببطء. أبقِ ظهر الركبة على اللفافة.",
    biomechanicalRationale:
      "Short-arc loading increases quadriceps activation with reduced patellofemoral stress vs deep flexion.",
    progressionCriteria: "Ready for clinician progression review when reps are smooth with full terminal extension.",
    regressionCriteria: "Reduce hold time or range if anterior knee pain increases.",
    futureCvMeasurementTarget: "knee extension hold, quad activation",
    libraryVersion: "v1",
  },
  {
    exerciseId: "lateral-band-walk",
    nameEn: "Lateral Band Walk",
    nameAr: "المشي الجانبي بشريط المقاومة",
    bodyRegion: "knee",
    conditionCategory: ["ACL", "knee valgus control", "hip-knee stability"],
    targetImpairment: "Hip abductor weakness and dynamic knee valgus",
    functionalGoal: "Improve side-to-side stability during walking and squatting",
    difficultyLevel: 2,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSec: 60,
    equipment: ["Loop band above knees or ankles"],
    precautions: "Keep knees aligned over feet. Stay in quarter-squat posture. Do not let knees collapse inward.",
    precautionsAr: "حافظ على محاذاة الركبتين مع القدمين. ابقَ في وضع قرفصاء خفيف. لا تدع الركبتين تنطويان للداخل.",
    contraindications: "Acute hip or lateral knee pain with resisted abduction.",
    whyThisMatters: "Hip and knee control during side steps helps prevent buckling and supports safer sports and stairs.",
    whyThisMattersAr: "التحكم في الورك والركبة أثناء الخطوات الجانبية يقلّل الانهيار ويدعم حركة أكثر أماناً.",
    patientInstructions:
      "Place a band above your knees. Sit into a slight squat. Step sideways while keeping tension on the band and knees over toes. Take prescribed steps one direction, then return.",
    patientInstructionsAr: "ضع شريطاً فوق الركبتين. اجلس في قرفصاء خفيف. خطُ للجانب مع الحفاظ على شدّ الشريط ومحاذاة الركبتين. نفّذ الخطوات المحددة ثم عد.",
    biomechanicalRationale:
      "Hip abductor and external rotator activation improves frontal-plane knee control during functional movement.",
    progressionCriteria: "Ready for clinician progression review when alignment is maintained for full distance.",
    regressionCriteria: "Higher band placement, shorter steps, or remove band if form breaks down.",
    futureCvMeasurementTarget: "knee valgus angle, hip abduction control",
    libraryVersion: "v1",
  },

  // ── Lumbar (10) ───────────────────────────────────────────────────────────
  {
    exerciseId: "diaphragmatic-breathing",
    nameEn: "Diaphragmatic Breathing",
    nameAr: "التنفس الحجابي",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "core activation", "stress-related tension"],
    targetImpairment: "Poor breathing pattern / trunk bracing",
    functionalGoal: "Calm system and support gentle core activation",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultDurationSec: 300,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Breathe comfortably. Do not force breath holds.",
    precautionsAr: "تنفس براحة. لا تُجبر نفسك على حبس النفس.",
    contraindications: "Acute respiratory distress; severe anxiety where breath focus worsens symptoms without supervision.",
    whyThisMatters: "Relaxed breathing can reduce muscle tension and help you move more comfortably.",
    whyThisMattersAr: "التنفس الهادئ قد يقلّل توتر العضلات ويساعدك على الحركة براحة أكبر.",
    patientInstructions:
      "Lie on your back with knees bent. Place one hand on your chest and one on your belly. Breathe in slowly through your nose so your belly rises. Exhale gently through your mouth.",
    patientInstructionsAr: "استلقِ على ظهرك وركبتيك مثنيتان. ضع يداً على الصدر وأخرى على البطن. تنفس ببطء من الأنف حتى يرتفع البطن. زفر بلطف من الفم.",
    biomechanicalRationale: "Diaphragmatic breathing supports parasympathetic tone and baseline core coordination.",
    progressionCriteria: "Ready for clinician progression review when pattern is consistent without breath holding.",
    regressionCriteria: "Shorten duration or perform seated if lying is uncomfortable.",
    futureCvMeasurementTarget: "respiratory rate, trunk relaxation",
    libraryVersion: "v1",
  },
  {
    exerciseId: "pelvic-tilt",
    nameEn: "Pelvic Tilt",
    nameAr: "ميل الحوض",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "lumbar stiffness"],
    targetImpairment: "Limited lumbar-pelvic control",
    functionalGoal: "Improve awareness of neutral spine position",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultReps: 15,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Move gently. Stay within a pain-free range.",
    precautionsAr: "تحرّك بلطف. ابقَ ضمن مدى خالٍ من الألم.",
    contraindications: "Suspected cauda equina or progressive neurological deficit — seek urgent medical review.",
    whyThisMatters: "Learning to move your pelvis gently helps reduce stiffness and supports safer bending.",
    whyThisMattersAr: "تعلّم تحريك الحوض بلطف يقلّل التصلّب ويدعم الانحناء بأمان أكبر.",
    patientInstructions:
      "Lie on your back, knees bent. Flatten your lower back toward the floor by gently tilting your pelvis. Hold 3 seconds, then release. Move slowly.",
    patientInstructionsAr: "استلقِ على ظهرك وركبتيك مثنيتان. اضغط أسفل الظهر نحو الأرض بميل الحوض بلطف. ثبّت 3 ثوانٍ ثم ارخِ. تحرّك ببطء.",
    biomechanicalRationale: "Low-load lumbopelvic mobilization for motor control of lumbar flexion-extension.",
    progressionCriteria: "Ready for clinician progression review when movement is smooth and symptom-stable.",
    regressionCriteria: "Reduce range if extension or flexion provokes symptoms.",
    futureCvMeasurementTarget: "lumbar flexion control",
    libraryVersion: "v1",
  },
  {
    exerciseId: "cat-cow",
    nameEn: "Cat-Cow",
    nameAr: "قطّة-بقرة",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "thoracic-lumbar mobility"],
    targetImpairment: "Spinal stiffness",
    functionalGoal: "Improve gentle spinal movement",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSec: 30,
    equipment: ["Mat"],
    precautions: "Avoid end-range pinching. Move with breath.",
    precautionsAr: "تجنّب الضغط الشديد في نهاية المدى. تحرّك مع التنفس.",
    contraindications: "Unstable spinal fracture; acute radicular pain worsened by flexion-extension.",
    whyThisMatters: "Gentle arching and rounding keeps your spine moving comfortably through the day.",
    whyThisMattersAr: "التقوس والتقوس العكسي بلطف يحافظ على مرونة العمود الفقري طوال اليوم.",
    patientInstructions:
      "On hands and knees, arch your back up like a cat, then slowly drop your belly and lift your chest. Move between positions with your breath.",
    patientInstructionsAr: "على يديك وركبتيك، قوّس ظهرك للأعلى كالقطة، ثم اخفض بطنك وارفع صدرك ببطء. تنقل بين الوضعين مع تنفسك.",
    biomechanicalRationale: "Alternating flexion-extension mobilization through low shear positions.",
    progressionCriteria: "Ready for clinician progression review when full range is comfortable.",
    regressionCriteria: "Reduce range if wrist or knee loading is problematic — modify position.",
    futureCvMeasurementTarget: "spinal segment motion",
    libraryVersion: "v1",
  },
  {
    exerciseId: "glute-bridge",
    nameEn: "Glute Bridge",
    nameAr: "جسر الأرداف",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "hip weakness"],
    targetImpairment: "Hip extension weakness",
    functionalGoal: "Strengthen glutes to support the lower back",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSec: 45,
    equipment: ["Mat"],
    precautions: "Do not over-arch the lower back at the top. Squeeze glutes, not low back.",
    precautionsAr: "لا تفرط في تقوس أسفل الظهر في الأعلى. شدّ الأرداف لا أسفل الظهر.",
    contraindications: "Acute hamstring tear; hip replacement precautions limiting hip extension.",
    whyThisMatters: "Strong glutes help support your lower back when you stand, walk, and lift.",
    whyThisMattersAr: "الأرداف القوية تدعم أسفل الظهر عند الوقوف والمشي والرفع.",
    patientInstructions:
      "Lie on your back, knees bent, feet flat. Lift your hips until shoulders, hips, and knees align. Squeeze your glutes at the top. Lower slowly.",
    patientInstructionsAr: "استلقِ على ظهرك، ركبتان مثنيتان وقدمان على الأرض. ارفع الوركين حتى تتساوى الكتفان والوركان والركبتان. شدّ الأرداف في الأعلى. انزل ببطء.",
    biomechanicalRationale: "Hip extension strengthening with reduced lumbar compression vs loaded squatting.",
    progressionCriteria: "Ready for clinician progression review when bridges are stable without cramping.",
    regressionCriteria: "Reduce height or perform partial range if hamstring cramp occurs.",
    futureCvMeasurementTarget: "hip extension, lumbar neutral",
    libraryVersion: "v1",
  },
  {
    exerciseId: "bird-dog",
    nameEn: "Bird-Dog",
    nameAr: "طائر-كلب",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "core stability"],
    targetImpairment: "Trunk stability deficit",
    functionalGoal: "Build core and hip control during arm/leg movement",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Mat"],
    precautions: "Keep trunk steady — avoid rocking. Stop if back pain increases.",
    precautionsAr: "ثبّت الجذع — تجنّب التأرجح. توقّف إذا زاد ألم الظهر.",
    contraindications: "Wrist or knee loading intolerance in quadruped; acute shoulder instability in weight-bearing through arms.",
    whyThisMatters: "This exercise trains your core to stay stable while your arms and legs move.",
    whyThisMattersAr: "هذا التمرين يدرّب وسط جسمك على الثبات أثناء حركة الذراعين والساقين.",
    patientInstructions:
      "On hands and knees, extend opposite arm and leg while keeping your trunk level. Hold 3 seconds, return, switch sides. Move slowly.",
    patientInstructionsAr: "على يديك وركبتيك، مدّ الذراع والساق المعاكسين مع الحفاظ على استقامة الجذع. ثبّت 3 ثوانٍ، ارجع، ثم بدّل الجانب. تحرّك ببطء.",
    biomechanicalRationale: "Anti-rotation and anti-extension challenge for deep stabilizers.",
    progressionCriteria: "Ready for clinician progression review when trunk stays level for full set.",
    regressionCriteria: "Lift arm or leg only (not both) if form breaks down.",
    futureCvMeasurementTarget: "trunk stability",
    libraryVersion: "v1",
  },
  {
    exerciseId: "hip-hinge",
    nameEn: "Hip Hinge (education)",
    nameAr: "ميل الورك",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "movement retraining"],
    targetImpairment: "Poor hip vs lumbar dissociation",
    functionalGoal: "Learn safe bending pattern using hips",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Wall or dowel optional"],
    precautions: "Keep spine neutral. Hinge at hips, not low back.",
    precautionsAr: "حافظ على استقامة العمود الفقري. انحنِ من الورك لا من أسفل الظهر.",
    contraindications: "Acute disc herniation with flexion intolerance until assessed by clinician.",
    whyThisMatters: "Bending from your hips protects your lower back during daily tasks.",
    whyThisMattersAr: "الانحناء من الورك يحمي أسفل الظهر في مهامك اليومية.",
    patientInstructions:
      "Stand with feet hip-width apart. Push hips back while keeping a slight knee bend and neutral spine, as if closing a door with your hips. Return to standing.",
    patientInstructionsAr: "قف بقدمين بعرض الوركين. ادفع الوركين للخلف مع ثني بسيط في الركبتين وعمود فقري محايد، كأنك تغلق باباً بالورك. عد للوقوف.",
    biomechanicalRationale: "Motor retraining for hip-dominant flexion reducing lumbar flexion moment.",
    progressionCriteria: "Ready for clinician progression review when pattern is consistent without lumbar rounding.",
    regressionCriteria: "Reduce range or use wall feedback if lumbar flexion occurs.",
    futureCvMeasurementTarget: "hip vs lumbar flexion",
    libraryVersion: "v1",
  },
  {
    exerciseId: "walking-tolerance",
    nameEn: "Walking Tolerance",
    nameAr: "تحمل المشي",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "deconditioning"],
    targetImpairment: "Reduced walking endurance",
    functionalGoal: "Build safe walking duration for daily activities",
    difficultyLevel: 1,
    defaultSets: 1,
    defaultDurationSec: 600,
    defaultRestSec: 0,
    equipment: [],
    precautions: "Walk at a comfortable pace. Stop and rest if symptoms flare beyond baseline.",
    precautionsAr: "امشِ بوتيرة مريحة. توقّف واسترح إذا زادت الأعراض عن المعتاد.",
    contraindications: "Unstable cardiovascular symptoms; physician-imposed activity restriction.",
    whyThisMatters: "Gradual walking helps you return to daily activities and supports overall recovery.",
    whyThisMattersAr: "المشي التدريجي يساعدك على العودة للأنشطة اليومية ويدعم تعافيك.",
    patientInstructions:
      "Walk at a comfortable pace on flat ground for the prescribed time. Stand tall, let arms swing naturally. Rest as needed.",
    patientInstructionsAr: "امشِ بوتيرة مريحة على أرض مستوية للمدة المحددة. قف مستقيماً ودع ذراعيك تتحرك طبيعياً. استرح عند الحاجة.",
    biomechanicalRationale: "Low-impact aerobic loading for tissue tolerance and confidence.",
    progressionCriteria: "Ready for clinician progression review when duration increases without symptom flare.",
    regressionCriteria: "Reduce time or break into shorter intervals.",
    futureCvMeasurementTarget: "gait speed, posture",
    libraryVersion: "v1",
  },
  {
    exerciseId: "dead-bug",
    nameEn: "Dead Bug",
    nameAr: "حشرة ميتة",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "core stability", "motor control"],
    targetImpairment: "Poor trunk stability with limb movement",
    functionalGoal: "Maintain neutral spine while moving arms and legs",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Mat"],
    precautions: "Keep low back gently pressed toward floor. Move slowly. Stop if back arches off the mat.",
    precautionsAr: "اضغط أسفل الظهر بلطف نحو الأرض. تحرّك ببطء. توقّف إذا ارتفع الظهر عن السجادة.",
    contraindications: "Supine intolerance; acute hip flexor spasm with bilateral leg lowering.",
    whyThisMatters: "Training your core in this position helps protect your back during rolling and reaching.",
    whyThisMattersAr: "تدريب وسط الجسم في هذا الوضع يحمي ظهرك أثناء التقلب والوصول.",
    patientInstructions:
      "Lie on your back, arms toward ceiling, hips and knees at 90°. Lower opposite arm and leg toward the floor while keeping your trunk steady. Return and switch sides.",
    patientInstructionsAr: "استلقِ على ظهرك، ذراعاك للأعلى، وركبتان ووركان عند 90°. اخفض الذراع والساق المعاكسين نحو الأرض مع ثبات الجذع. ارجع وبدّل الجانب.",
    biomechanicalRationale:
      "Supine anti-extension challenge with alternating limb load for deep core coordination.",
    progressionCriteria: "Ready for clinician progression review when lumbar contact stays stable for full set.",
    regressionCriteria: "Move arm or leg only, or reduce range if back arches.",
    futureCvMeasurementTarget: "lumbar flexion control, limb angle symmetry",
    libraryVersion: "v1",
  },
  {
    exerciseId: "side-plank",
    nameEn: "Side Plank (modified)",
    nameAr: "البلانك الجانبي (معدّل)",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "lateral core", "hip stability"],
    targetImpairment: "Lateral trunk and hip stability deficit",
    functionalGoal: "Build side support for walking and lifting",
    difficultyLevel: 2,
    defaultSets: 2,
    defaultDurationSec: 20,
    defaultRestSec: 45,
    equipment: ["Mat"],
    precautions: "Keep body in straight line from knees or feet. Breathe steadily. Stop if shoulder pain occurs.",
    precautionsAr: "حافظ على خط مستقيم من الركبتين أو القدمين. تنفس بانتظام. توقّف عند ألم في الكتف.",
    contraindications: "Acute shoulder weight-bearing intolerance; painful hip abductor tear.",
    whyThisMatters: "Side strength helps you stay upright when carrying bags or stepping off curbs.",
    whyThisMattersAr: "قوة الجانب تساعدك على البقاء مستقيماً عند حمل الأشياء أو النزول من الرصيف.",
    patientInstructions:
      "Lie on your side, forearm on the mat, knees bent (easier) or legs straight. Lift hips until body forms a straight line. Hold for the prescribed time, then lower.",
    patientInstructionsAr: "استلقِ على جانبك، ساعدك على السجادة، ركبتان مثنيتان (أسهل) أو ساقان مستقيمتان. ارفع الوركين حتى يصبح الجسم خطاً مستقيماً. ثبّت للمدة المحددة ثم انزل.",
    biomechanicalRationale:
      "Lateral chain isometric loading for quadratus lumborum and glute medius without spinal compression.",
    progressionCriteria: "Ready for clinician progression review when hold time meets target with level hips.",
    regressionCriteria: "Bent-knee version or shorter holds if form collapses.",
    futureCvMeasurementTarget: "hip height symmetry, trunk lateral alignment",
    libraryVersion: "v1",
  },
  {
    exerciseId: "prone-press-up",
    nameEn: "Prone Press-Up (Extension)",
    nameAr: "الضغط على البطن (تمديد)",
    bodyRegion: "lumbar",
    conditionCategory: ["LBP", "extension preference", "disc-related LBP"],
    targetImpairment: "Extension intolerance or stiffness in extension-biased LBP",
    functionalGoal: "Restore comfortable backward bending when appropriate",
    difficultyLevel: 2,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Mat"],
    precautions: "Keep hips on the mat. Press with arms only. Stop immediately if leg symptoms worsen.",
    precautionsAr: "أبقِ الوركين على السجادة. ادفع بالذراعين فقط. توقّف فوراً إذا ساءت أعراض الساق.",
    contraindications: "Centralization worsens with extension; spinal stenosis with extension intolerance; spondylolisthesis unless cleared.",
    whyThisMatters: "When your clinician approves extension, this can reduce stiffness and improve upright posture.",
    whyThisMattersAr: "عند موافقة المعالج، قد يقلّل هذا التمرين التصلّب ويحسّن وضعية الوقوف.",
    patientInstructions:
      "Lie face down, hands under shoulders. Gently press up, lifting chest while hips stay down. Go to a comfortable height, then lower. Move within symptom-free range.",
    patientInstructionsAr: "استلقِ على بطنك ويداك تحت الكتفين. ادفع بلطف لرفع الصدر مع بقاء الوركين للأسفل. اذهب لارتفاع مريح ثم انزل. تحرّك ضمن مدى خالٍ من الألم.",
    biomechanicalRationale:
      "Repeated extension in lying can centralize symptoms in extension-responsive low back pain presentations.",
    progressionCriteria: "Ready for clinician progression review when extension range improves without peripheral symptom spread.",
    regressionCriteria: "Smaller range or fewer reps if symptoms peripheralize.",
    futureCvMeasurementTarget: "lumbar extension ROM",
    libraryVersion: "v1",
  },

  // ── Shoulder (8) ──────────────────────────────────────────────────────────
  {
    exerciseId: "pendulum",
    nameEn: "Pendulum Exercise",
    nameAr: "تأرجح الذراع",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder pain", "post-op shoulder", "frozen shoulder"],
    targetImpairment: "Shoulder stiffness",
    functionalGoal: "Gentle passive shoulder mobility",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultDurationSec: 120,
    defaultRestSec: 30,
    equipment: ["Table or chair for support"],
    precautions: "Let arm hang relaxed. Do not force circular motion.",
    precautionsAr: "دع الذراع تتدلى مرتاحة. لا تُجبر الحركة الدائرية.",
    contraindications: "Acute shoulder dislocation; post-operative shoulder precautions until cleared.",
    whyThisMatters: "Gentle swinging helps loosen a stiff shoulder without heavy muscle effort.",
    whyThisMattersAr: "التأرجح اللطيف يساعد على تخفيف تصلّب الكتف دون جهد عضلي كبير.",
    patientInstructions:
      "Lean forward, support yourself with the unaffected arm on a table. Let the affected arm hang and gently swing in small circles. Keep shoulder relaxed.",
    patientInstructionsAr: "انحنِ للأمام وادعم نفسك بالذراع السليمة على طاولة. دع الذراع المصابة تتدلى وتأرجح في دوائر صغيرة. أبقِ الكتف مرتاحاً.",
    biomechanicalRationale: "Gravity-assisted passive mobility with minimal active contraction.",
    progressionCriteria: "Ready for clinician progression review when range improves comfortably.",
    regressionCriteria: "Smaller circles or shorter duration if pain increases.",
    futureCvMeasurementTarget: "passive shoulder circumduction range",
    libraryVersion: "v1",
  },
  {
    exerciseId: "scapular-setting",
    nameEn: "Scapular Setting",
    nameAr: "تثبيت الكتف",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder impingement", "posture", "rotator cuff"],
    targetImpairment: "Scapular dyskinesis",
    functionalGoal: "Improve shoulder blade control and posture",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Do not shrug toward ears. Gentle squeeze downward and back.",
    precautionsAr: "لا ترفع الكتفين نحو الأذنين. شدّ بلطف للأسفل والخلف.",
    contraindications: "Acute cervical radiculopathy aggravated by shoulder retraction.",
    whyThisMatters: "Good shoulder blade position supports healthy shoulder movement and posture.",
    whyThisMattersAr: "وضع لوح الكتف الجيد يدعم حركة الكتف الصحية والوضعية.",
    patientInstructions:
      "Sit or stand tall. Gently draw shoulder blades down and slightly together, as if putting them in back pockets. Hold 5 seconds, relax.",
    patientInstructionsAr: "اجلس أو قف باستقامة. اسحب لوحي الكتف بلطف للأسفل وقربهما قليلاً، كأنك تضعهما في جيب خلفي. ثبّت 5 ثوانٍ ثم ارخِ.",
    biomechanicalRationale: "Activates lower trapezius and serratus for scapular stability.",
    progressionCriteria: "Ready for clinician progression review when hold is consistent without upper trap dominance.",
    regressionCriteria: "Shorter holds if neck tension occurs.",
    futureCvMeasurementTarget: "scapular position",
    libraryVersion: "v1",
  },
  {
    exerciseId: "table-slide",
    nameEn: "Table Slides (Flexion)",
    nameAr: "انزلاق على الطاولة",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder stiffness", "post-op shoulder"],
    targetImpairment: "Limited shoulder flexion",
    functionalGoal: "Improve reaching overhead safely",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSec: 45,
    equipment: ["Table"],
    precautions: "Slide within comfort. Do not force overhead range.",
    precautionsAr: "انزلق ضمن راحتك. لا تُجبر الذراع على مدى فوق الرأس.",
    contraindications: "Recent rotator cuff repair with flexion restrictions.",
    whyThisMatters: "Table slides help you regain reaching movement with support and less pain.",
    whyThisMattersAr: "الانزلاق على الطاولة يساعدك على استعادة الوصول للأعلى بدعم وألم أقل.",
    patientInstructions:
      "Sit at a table, place hands on a towel. Slide hands forward along the table, allowing arms to rise. Go to comfortable height, then slide back.",
    patientInstructionsAr: "اجلس عند طاولة وضع يديك على منشفة. انزلق يديك للأمام على الطاولة ليرتفع الذراعان. اذهب لارتفاع مريح ثم ارجع.",
    biomechanicalRationale: "Assisted flexion reduces active torque while improving ROM.",
    progressionCriteria: "Ready for clinician progression review when flexion range improves steadily.",
    regressionCriteria: "Reduce slide distance if pinching occurs.",
    futureCvMeasurementTarget: "shoulder flexion ROM",
    libraryVersion: "v1",
  },
  {
    exerciseId: "external-rotation",
    nameEn: "External Rotation (Band)",
    nameAr: "دوران خارجي",
    bodyRegion: "shoulder",
    conditionCategory: ["rotator cuff", "shoulder stability"],
    targetImpairment: "Rotator cuff weakness",
    functionalGoal: "Strengthen outward rotation for shoulder stability",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSec: 45,
    equipment: ["Resistance band", "Towel roll under arm optional"],
    precautions: "Keep elbow at side. Slow controlled movement. Light resistance only.",
    precautionsAr: "أبقِ المرفق بجانب الجسم. حركة بطيئة ومتحكّمة. مقاومة خفيفة فقط.",
    contraindications: "Post-operative external rotation precautions; acute biceps tendon irritation.",
    whyThisMatters: "Strong rotator cuff muscles help keep the shoulder stable during daily tasks.",
    whyThisMattersAr: "عضلات الكuff الدوار القوية تساعد على ثبات الكتف في مهامك اليومية.",
    patientInstructions:
      "Elbow bent at 90°, tucked at your side. Rotate forearm outward against band resistance. Return slowly. Keep elbow fixed.",
    patientInstructionsAr: "مرفق مثني 90° ومثبت بجانبك. أدِر الساعد للخارج ضد مقاومة الشريط. ارجع ببطء. ثبّت المرفق.",
    biomechanicalRationale: "Targets infraspinatus/teres minor for glenohumeral stability.",
    progressionCriteria: "Ready for clinician progression review when full set with good form.",
    regressionCriteria: "Lighter band or fewer reps if pain at end range.",
    futureCvMeasurementTarget: "external rotation ROM",
    libraryVersion: "v1",
  },
  {
    exerciseId: "wall-slide",
    nameEn: "Wall Slides",
    nameAr: "انزلاق على الحائط",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder impingement", "posture"],
    targetImpairment: "Overhead mobility with poor scapular control",
    functionalGoal: "Improve overhead reach with scapular upward rotation",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSec: 45,
    equipment: ["Wall"],
    precautions: "Keep contact with wall. Do not arch lower back excessively.",
    precautionsAr: "حافظ على ملامسة الحائط. لا تفرط في تقوس أسفل الظهر.",
    contraindications: "Impingement with painful end-range elevation until modified range is prescribed.",
    whyThisMatters: "Wall slides train safe overhead movement with good posture.",
    whyThisMattersAr: "الانزلاق على الحائط يدرّب الوصول للأعلى بأمان ووضعية جيدة.",
    patientInstructions:
      "Stand with back against wall, arms in W shape. Slide arms up the wall toward a Y shape, then back down. Keep wrists and elbows near wall.",
    patientInstructionsAr: "قف بظهرك على الحائط وذراعاك بشكل W. انزلق ذراعيك على الحائط نحو Y ثم انزل. أبقِ المعصمين والمرفقين قريبين من الحائط.",
    biomechanicalRationale: "Combines flexion with scapular upward rotation in closed-environment feedback.",
    progressionCriteria: "Ready for clinician progression review when overhead range improves without compensation.",
    regressionCriteria: "Partial range if lumbar extension or pain occurs.",
    futureCvMeasurementTarget: "scapular upward rotation",
    libraryVersion: "v1",
  },
  {
    exerciseId: "posture-reset",
    nameEn: "Posture Reset",
    nameAr: "إعادة ضبط الوضعية",
    bodyRegion: "shoulder",
    conditionCategory: ["posture", "neck-shoulder tension"],
    targetImpairment: "Forward head / rounded shoulder posture",
    functionalGoal: "Practice neutral alignment for daily activities",
    difficultyLevel: 1,
    defaultSets: 3,
    defaultDurationSec: 30,
    defaultRestSec: 20,
    equipment: [],
    precautions: "Gentle chin tuck — do not force neck backward.",
    precautionsAr: "سحب الذقن بلطف — لا تدفع الرقبة للخلف بقوة.",
    contraindications: "Acute cervical spine instability or severe dizziness with head repositioning.",
    whyThisMatters: "Good posture reduces strain on your neck and shoulders during the day.",
    whyThisMattersAr: "الوضعية الجيدة تقلّل الإجهاد على الرقبة والكتفين خلال اليوم.",
    patientInstructions:
      "Sit or stand tall. Gently draw chin back, lengthen spine, relax shoulders down. Breathe steadily and hold comfortable alignment.",
    patientInstructionsAr: "اجلس أو قف باستقامة. اسحب ذقنك بلطف للخلف، اطوّل العمود الفقري، وارخِ الكتفين. تنفس بانتظام وحافظ على وضع مريح.",
    biomechanicalRationale: "Cervicothoracic alignment retraining for load distribution.",
    progressionCriteria: "Ready for clinician progression review when posture can be maintained during light activity.",
    regressionCriteria: "Shorter holds if neck tension occurs.",
    futureCvMeasurementTarget: "cervical alignment, shoulder elevation",
    libraryVersion: "v1",
  },
  {
    exerciseId: "internal-rotation",
    nameEn: "Internal Rotation (Band)",
    nameAr: "الدوران الداخلي بشريط",
    bodyRegion: "shoulder",
    conditionCategory: ["rotator cuff", "shoulder stability", "post-op shoulder"],
    targetImpairment: "Subscapularis / internal rotation weakness",
    functionalGoal: "Balance rotator cuff strength for shoulder control",
    difficultyLevel: 2,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSec: 45,
    equipment: ["Resistance band", "Towel roll under arm optional"],
    precautions: "Elbow stays at side at 90°. Slow return. Light resistance only.",
    precautionsAr: "يبقى المرفق بجانب الجسم عند 90°. ارجع ببطء. مقاومة خفيفة فقط.",
    contraindications: "Post-operative internal rotation restrictions; acute anterior shoulder pain at end range.",
    whyThisMatters: "Balanced rotator cuff strength on both sides keeps the shoulder stable during daily tasks.",
    whyThisMattersAr: "توازن قوة الكuff الدوار من الجانبين يحافظ على ثبات الكتف.",
    patientInstructions:
      "Anchor band at elbow height. Stand with elbow bent 90°, tucked at your side. Rotate forearm inward across your body against band resistance. Return slowly.",
    patientInstructionsAr: "ثبّت الشريط على ارتفاع المرفق. قف بمرفق مثني 90° بجانبك. أدِر الساعد للداخل عبر الجسم ضد الشريط. ارجع ببطء.",
    biomechanicalRationale:
      "Targets subscapularis for glenohumeral compression and internal rotation balance with external rotators.",
    progressionCriteria: "Ready for clinician progression review when full set completed with stable scapula.",
    regressionCriteria: "Lighter band or partial range if anterior shoulder pain occurs.",
    futureCvMeasurementTarget: "internal rotation ROM",
    libraryVersion: "v1",
  },
  {
    exerciseId: "cross-body-stretch",
    nameEn: "Cross-Body Stretch",
    nameAr: "تمديد عبر الجسم",
    bodyRegion: "shoulder",
    conditionCategory: ["shoulder stiffness", "posterior cuff", "post-op shoulder"],
    targetImpairment: "Posterior shoulder tightness",
    functionalGoal: "Improve comfortable horizontal adduction for reaching across body",
    difficultyLevel: 1,
    defaultSets: 2,
    defaultDurationSec: 30,
    defaultRestSec: 30,
    equipment: [],
    precautions: "Gentle stretch only — do not force arm across body. Keep shoulder relaxed.",
    precautionsAr: "تمدّد لطيف فقط — لا تُجبر الذراع عبر الجسم. أبقِ الكتف مرتاحاً.",
    contraindications: "Acute posterior shoulder pain; unstable shoulder with painful cross-body motion.",
    whyThisMatters: "Gentle stretching can ease tightness so you can reach across your body more comfortably.",
    whyThisMattersAr: "التمدّد اللطيف قد يخفّف الشد ويساعدك على الوصول عبر جسمك براحة أكبر.",
    patientInstructions:
      "Bring the affected arm across your chest. Use the other hand to gently press above the elbow. Hold a comfortable stretch. Keep shoulders down and relaxed.",
    patientInstructionsAr: "أحضِ الذراع المصابة عبر صدرك. استخدم اليد الأخرى للضغط بلطف فوق المرفق. ثبّت تمدّداً مريحاً. أبقِ الكتفين للأسفل ومرتاحين.",
    biomechanicalRationale:
      "Low-load static stretch of posterior deltoid and infraspinatus/teres minor complex.",
    progressionCriteria: "Ready for clinician progression review when range improves without pain after stretch.",
    regressionCriteria: "Shorter holds or less pressure if stretch provokes symptoms.",
    futureCvMeasurementTarget: "horizontal adduction ROM",
    libraryVersion: "v1",
  },
];

const LIBRARY_BY_ID = new Map(EXERCISE_LIBRARY_V1.map((e) => [e.exerciseId, e]));

export function getLibraryExerciseById(exerciseId: string): ExerciseLibraryEntryV1 | null {
  return LIBRARY_BY_ID.get(exerciseId) ?? null;
}

export function getLibraryExercisesByRegion(region: BodyRegion | "all"): ExerciseLibraryEntryV1[] {
  if (region === "all") return EXERCISE_LIBRARY_V1;
  return EXERCISE_LIBRARY_V1.filter((e) => e.bodyRegion === region);
}
