/**
 * session-plan.ts — Prescribed Session Program V1
 *
 * Generates and persists one active rehabilitation session plan per patient.
 * Plans are auto-generated from the gait progression recommendation engine
 * and stored in localStorage per patient.
 *
 * Structure is designed for future therapist override compatibility:
 *   • prescribedBy: "auto" | "therapist"
 *   • A therapistOverrides slot is reserved in the type for V2.
 *
 * Decision-support only · Not a clinical prescription.
 * All targets are advisory. Therapist review is required before
 * communicating formal goals to patients.
 */

import type { SessionRecord } from "../session-store";
import {
  recommendExercise,
  getExercise,
  type CVMetricKey,
  type GaitExercise,
  type SuccessRule,
} from "./gait-progression";
import { PROGRAMS, type ProgramId } from "../programs";

/* ═══════════════════════════════════════════════════════════════════════════
   Types
═══════════════════════════════════════════════════════════════════════════ */

/**
 * A single measurable target within a session plan.
 * Derived directly from the exercise's success rules.
 */
export interface SessionTarget {
  metric:          CVMetricKey;
  operator:        ">=" | "<=" | "range";
  threshold:       number;
  thresholdMax?:   number;
  /** Human-readable label shown in the session UI: "Symmetry ≥ 72%" */
  label:           string;
  /** Brief clinical reason shown in the progress report. */
  description:     string;
  /**
   * True if this metric is available as a live value during the session
   * (totalSteps, symmetryPct, stepsPerMin are real-time; biomechanics scores
   * are computed only at session end).
   */
  isLiveTrackable: boolean;
}

/** Active session prescription for one patient. */
export interface SessionPlan {
  id:                string;
  patientId:         string;
  /**
   * Stable identifier of the rehabilitation program this plan belongs to.
   * Set to PROGRAMS.GAIT_TRAINING.id ("gait_training") by generateSessionPlan()
   * unless overridden.
   *
   * Optional for backward compatibility: plans generated before this field was
   * introduced have no programId. Treat them as "gait_training".
   *
   * Integration note: the main platform will use this to scope prescriptions
   * to the correct program and therapist workflow.
   */
  programId?:        ProgramId;
  /** ISO 8601 timestamp of plan generation. */
  generatedAt:       string;
  exerciseId:        string;
  exerciseName:      string;
  /** 2–3 targets derived from the exercise's success rules. */
  targets:           SessionTarget[];
  /** Short coaching cues shown in-game. Max 1 for V1 — keeps the UI clean. */
  coachingCues:      string[];
  /** One-sentence clinical rationale from the recommendation engine. */
  clinicalRationale: string;
  /**
   * "auto" = generated by the recommendation engine.
   * "therapist" = manually prescribed (V2 — reserved slot).
   */
  prescribedBy:      "auto" | "therapist";
  status:            "active" | "completed" | "skipped";
  // Future V2 override hook:
  // therapistOverrides?: Partial<Pick<SessionPlan, "targets" | "exerciseId" | "coachingCues">>;
}

/* ═══════════════════════════════════════════════════════════════════════════
   Internal helpers
═══════════════════════════════════════════════════════════════════════════ */

/** Metrics available as real-time values during the session. */
const LIVE_TRACKABLE: ReadonlySet<CVMetricKey> = new Set<CVMetricKey>([
  "totalSteps",
  "symmetryPct",
  "stepsPerMin",
]);

const METRIC_FRIENDLY_NAMES: Partial<Record<CVMetricKey, string>> = {
  totalSteps:           "Total Steps",
  symmetryPct:          "Symmetry",
  stepsPerMin:          "Cadence",
  fatigueIndex:         "Fatigue Index",
  romScore:             "ROM Score",
  postureScore:         "Posture Score",
  controlScore:         "Control Score",
  symmetryScore:        "Symmetry Score",
  movementQualityScore: "Quality Score",
  avgKneeAngle:         "Knee Angle",
  kneeAngleAsymmetry:   "Knee Asymmetry",
};

function metricUnit(metric: CVMetricKey): string {
  if (metric === "symmetryPct" || metric === "symmetryScore") return "%";
  if (metric === "stepsPerMin") return " spm";
  if (metric === "fatigueIndex") return "";
  return "";
}

function makeTargetLabel(rule: SuccessRule): string {
  const name = METRIC_FRIENDLY_NAMES[rule.metric] ?? rule.metric;
  const unit = metricUnit(rule.metric);
  if (rule.operator === "range") {
    return `${name} ${rule.threshold}–${rule.thresholdMax}${unit}`;
  }
  return `${name} ${rule.operator} ${rule.threshold}${unit}`;
}

/**
 * Select 2–3 targets from an exercise's success rules, prioritising:
 *   1. The exercise's primary metric (most clinically relevant)
 *   2. Symmetry (always clinically important)
 *   3. A live-trackable step count or cadence metric
 *   4. Any remaining rule up to the 3-target cap
 */
function selectTargets(exercise: GaitExercise): SessionTarget[] {
  const rules = exercise.successRules;
  const selected: SuccessRule[] = [];

  const tryAdd = (metric: CVMetricKey) => {
    if (selected.length >= 3) return;
    const r = rules.find((ru) => ru.metric === metric && !selected.includes(ru));
    if (r) selected.push(r);
  };

  // 1. Primary metric
  tryAdd(exercise.primaryMetric);
  // 2. Symmetry
  tryAdd("symmetryPct");
  // 3. Live step count or cadence
  tryAdd("totalSteps");
  tryAdd("stepsPerMin");
  // 4. Fallback — any remaining rule
  for (const r of rules) {
    if (!selected.includes(r) && selected.length < 3) selected.push(r);
  }

  return selected.map((r) => ({
    metric:          r.metric,
    operator:        r.operator as ">=" | "<=" | "range",
    threshold:       r.threshold,
    thresholdMax:    r.thresholdMax,
    label:           makeTargetLabel(r),
    description:     r.description,
    isLiveTrackable: LIVE_TRACKABLE.has(r.metric),
  }));
}

/* ═══════════════════════════════════════════════════════════════════════════
   Plan generation
═══════════════════════════════════════════════════════════════════════════ */

/**
 * Generate a new session plan for a patient based on their session history.
 * Uses the gait progression recommendation engine to select the exercise.
 * Falls back to High Knee March (baseline) if no recommendation is available.
 */
export function generateSessionPlan(
  patientId: string,
  sessions:  SessionRecord[],
): SessionPlan {
  // Default exercise for new patients or when recommendation engine has no result
  const defaultExercise = getExercise("high_knee_march")!;

  const rec      = recommendExercise({ sessions });
  const exercise = rec?.exercise ?? defaultExercise;

  // Fallback rationale (only used when the recommendation engine returns null).
  // Language is cautious for the very first session since no prior data exists.
  const fallbackRationale = sessions.length === 0
    ? "First session — High Knee March will establish baseline gait data. " +
      "No prior metrics available. Results will guide future session targets and progression."
    : "High Knee March is the recommended baseline exercise for re-establishing gait patterns and bilateral coordination.";

  const rationale = rec?.clinicalRationale ?? fallbackRationale;

  return {
    id:                `plan-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 5)}`,
    patientId,
    // Always set on new plans. Caller can override for future multi-program support.
    programId:         PROGRAMS.GAIT_TRAINING.id,
    generatedAt:       new Date().toISOString(),
    exerciseId:        exercise.id,
    exerciseName:      exercise.name,
    targets:           selectTargets(exercise),
    coachingCues:      [exercise.clinicalCueShort],
    clinicalRationale: rationale,
    prescribedBy:      "auto",
    status:            "active",
  };
}

/* ═══════════════════════════════════════════════════════════════════════════
   Target evaluation
═══════════════════════════════════════════════════════════════════════════ */

/**
 * Extract the actual value for a target metric from a completed session.
 * Returns −1 for metrics that cannot be computed (e.g. missing biomechanics),
 * so that ">= threshold" rules safely fail for those sessions.
 */
export function getMetricActualValue(
  metric:  CVMetricKey,
  session: Pick<SessionRecord, "totalSteps" | "symmetryPct" | "stepsPerMin" |
                                "fatigueIndex" | "cameraVisibilityScore" | "biomechanics">,
): number {
  const bio = session.biomechanics;
  switch (metric) {
    case "totalSteps":           return session.totalSteps;
    case "symmetryPct":          return session.symmetryPct;
    case "stepsPerMin":          return session.stepsPerMin;
    case "fatigueIndex":         return session.fatigueIndex         ?? 0;
    case "cameraVisibilityScore":return session.cameraVisibilityScore ?? 0;
    case "romScore":             return bio?.romScore             ?? -1;
    case "postureScore":         return bio?.postureScore         ?? -1;
    case "controlScore":         return bio?.controlScore         ?? -1;
    case "symmetryScore":        return bio?.symmetryScore        ?? -1;
    case "movementQualityScore": return bio?.movementQualityScore ?? -1;
    default:                     return -1;
  }
}

function checkTarget(target: SessionTarget, actual: number): boolean {
  if (actual < 0) return false; // metric unavailable
  switch (target.operator) {
    case ">=":    return actual >= target.threshold;
    case "<=":    return actual <= target.threshold;
    case "range": return actual >= target.threshold &&
                         actual <= (target.thresholdMax ?? Infinity);
    default:      return false;
  }
}

/**
 * Evaluate a plan's targets against a completed session.
 * Returns a plain-object array that is safe to store in JSON / localStorage.
 */
export function evaluatePlanTargets(
  plan:    SessionPlan,
  session: Pick<SessionRecord, "totalSteps" | "symmetryPct" | "stepsPerMin" |
                                "fatigueIndex" | "cameraVisibilityScore" | "biomechanics">,
): Array<{
  metric:       string;
  label:        string;
  threshold:    number;
  thresholdMax: number | undefined;
  operator:     string;
  actualValue:  number;
  achieved:     boolean;
}> {
  return plan.targets.map((t) => {
    const actual = getMetricActualValue(t.metric, session);
    return {
      metric:       t.metric,
      label:        t.label,
      threshold:    t.threshold,
      thresholdMax: t.thresholdMax,
      operator:     t.operator,
      actualValue:  Math.round(actual * 10) / 10,
      achieved:     checkTarget(t, actual),
    };
  });
}

/* ═══════════════════════════════════════════════════════════════════════════
   localStorage persistence
═══════════════════════════════════════════════════════════════════════════ */

const PLAN_KEY_PREFIX = "cm_plan_v1_";

function isClient(): boolean {
  return typeof window !== "undefined";
}

/** Load the active plan for a patient. Returns null if none exists or it is not active. */
export function loadActivePlan(patientId: string): SessionPlan | null {
  if (!isClient()) return null;
  try {
    const raw  = localStorage.getItem(`${PLAN_KEY_PREFIX}${patientId}`);
    if (!raw) return null;
    const plan = JSON.parse(raw) as SessionPlan;
    return plan.status === "active" ? plan : null;
  } catch {
    return null;
  }
}

/** Persist a plan to localStorage (overwrites any existing plan for this patient). */
export function saveActivePlan(plan: SessionPlan): void {
  if (!isClient()) return;
  localStorage.setItem(`${PLAN_KEY_PREFIX}${plan.patientId}`, JSON.stringify(plan));
}

/** Mark the current plan as completed. */
export function completePlan(patientId: string): void {
  if (!isClient()) return;
  try {
    const raw = localStorage.getItem(`${PLAN_KEY_PREFIX}${patientId}`);
    if (!raw) return;
    const plan = JSON.parse(raw) as SessionPlan;
    plan.status = "completed";
    localStorage.setItem(`${PLAN_KEY_PREFIX}${patientId}`, JSON.stringify(plan));
  } catch { /* ignore */ }
}

/**
 * Load the active plan for a patient, or generate and persist a new one if
 * none exists. This is the primary entry point for both the session and
 * progress pages.
 */
export function loadOrGeneratePlan(
  patientId: string,
  sessions:  SessionRecord[],
): SessionPlan {
  const existing = loadActivePlan(patientId);
  if (existing) return existing;
  const plan = generateSessionPlan(patientId, sessions);
  saveActivePlan(plan);
  return plan;
}
