export {
  extractMotionInputSourceFromStructuredData,
  getMotionInputAdapter,
  getMotionInputAdapterOrNull,
  isKnownMotionInputAdapterId,
  isMotionInputAdapterId,
  isMotionInputCompatibleWithMode,
  listMotionInputAdapters,
  MOTION_INPUT_ADAPTER_IDS,
  MOTION_INPUT_SOURCE_METADATA_KEY,
  validateMotionInputModeCompatibility,
  MANUAL_CLINICIAN_ADAPTER,
  REMOTE_QUESTIONNAIRE_ADAPTER,
  WEB_CAMERA_POSE_ADAPTER,
  type AssessmentDeliveryContext,
  type AssessmentDeliveryKind,
  type MotionInputAdapterDescriptor,
  type MotionInputAdapterId,
} from "./motion-input-registry";
