/**
 * Shared clinical report copy — UI labels only (no schema keys).
 */

export const CLINICAL_REPORT_TITLE = "Clinical Assessment Report";

export const CLINICAL_REPORT_SUBTITLE =
  "Generated by RASQ — Clinical Decision-Support Tool";

export const CLINICAL_REPORT_INTRO =
  "This report supports clinician review and does not replace clinical judgment.";

export const CLINICAL_DISCLAIMER_SHORT =
  "Clinical decision-support draft — review all patient-reported and clinician-entered data before assigning a rehabilitation plan.";

export const CLINICAL_DISCLAIMER_FULL =
  "This report is generated from patient-reported and clinician-entered assessment data as a clinical decision-support draft. It does not constitute a medical diagnosis or treatment prescription. All clinical decisions remain the responsibility of the treating physiotherapist.";

export const LABEL_PATIENT_REPORTED_PREFIX = "Patient-reported";

export const LABEL_THERAPIST_CLINICAL_IMPRESSION = "Therapist-entered clinical impression";

export const LEGACY_IMPRESSION_NOTE =
  "Entered by clinician; not generated by RASQ.";

export const SECTION_OVERVIEW = "Patient & Assessment Overview";

export const PATIENT_REPORTED_INTRO =
  "Information below was submitted by the patient. It is not objective examination findings unless confirmed by the treating physiotherapist.";

export const SECTION_PATIENT_REPORTED_SUMMARY = "Patient-Reported Summary";

export const SECTION_ASSESSMENT_INTERPRETATION_DRAFT = "Assessment Interpretation Draft";

export const INTERPRETATION_DRAFT_BADGE = "Draft only — therapist confirmation required";

export const INTERPRETATION_DRAFT_INTRO =
  "Structured physiotherapy review prompts derived from patient-reported answers. This is not a diagnosis, does not replace clinical examination, and requires therapist confirmation before use.";

export const INTERPRETATION_DRAFT_FUNCTIONAL_HEADING = "Patient-reported functional limitations";

export const INTERPRETATION_DRAFT_MOVEMENT_HEADING =
  "Movement components that may be relevant to assess";

export const INTERPRETATION_DRAFT_MUSCLE_HEADING =
  "Possible muscle performance areas for therapist review";

export const INTERPRETATION_DRAFT_OBJECTIVE_HEADING = "Suggested objective therapist assessment items";

export const INTERPRETATION_DRAFT_EMPTY_NOTE =
  "Insufficient patient-reported detail to generate structured review prompts. Confirm findings during clinical examination.";

export const SECTION_CLINICAL_FINDINGS = "Clinical Findings / Therapist Input";

export const SECTION_SAFETY_INDICATORS = "Safety Indicators";

export const SECTION_SUGGESTED_DIRECTION = "Suggested Rehabilitation Direction";

export const SAFETY_REVIEW_REQUIRED =
  "Clinical review required before program assignment.";

export const SAFETY_NONE_DOCUMENTED =
  "No red flags documented in this assessment.";

export const SUGGESTED_DIRECTION_INTRO =
  "The following program options are surfaced from available assessment context and must be reviewed and adapted by the treating physiotherapist before assignment.";

export const SUGGESTED_DIRECTION_NO_MATCH =
  "No program option was automatically highlighted from assessment text. Review all available program options based on your clinical assessment.";

export const SUGGESTED_DIRECTION_MATCH_NOTE =
  "Options below were highlighted from assessment text for therapist review only.";

export const BADGE_FOR_THERAPIST_REVIEW = "For therapist review";

export const RED_FLAG_PATIENT_REPORTED =
  "Patient-reported information may indicate a red flag — clinical review required before program assignment.";

export const REPORT_NEXT_STEPS = [
  "Review patient-reported information",
  "Confirm clinical findings",
  "Select or adapt rehabilitation plan",
  "Monitor patient-reported pain and effort",
  "Review flags as needed",
] as const;

export function patientReportedLabel(field: string): string {
  return `${LABEL_PATIENT_REPORTED_PREFIX} · ${field}`;
}

export function therapistEnteredLabel(field: string): string {
  return `Therapist-entered · ${field}`;
}
